---
title: "Final Project Milestone 2"
author: "Debi Gonzalez"
date: "March 29, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Github repo with Rmd (and knitted html) which discusses pros and cons of at least two projects from last year. At least one project should be one which did extensive data gathering/cleaning. 
```

### Project 1
Saiyaz Kazi's final project - "Immigrant Voting Preferences by State" - explores interesting voting patterns among naturalized immigrants across the United States for the 2016 election by state. Based on his repo description, he did a fair amount of data cleaning and manipulation in order to make his data usable for his purpose. Using 2016 general election data from the American National Election Studies Survey, Saiyaz filtered for immigrant responses and then grouped the data by state. Despite the interesting data and extensive manipulation of the large dataset to adjust to his purpose, this student missed a few key points that would have further professionalized his project. The choice of y-axis variable seemed a bit confusing. It did not put into perspective the number of immigrants in the given state, and the ratio of political affiliations is unclear when the single bar for the party takes over the entire graph. The student also did not assign colors to each party, but rather let it be assigned automatically, which made Republicans blue in some states where there was no Democrat vote strength. This last part was quite confusing. I would say this project would have benefitted from a different kind of graphical representation. A map with immigrant population density would have added an interesting aspect that is missed by the raw ratio numbers. I think a jitter plot or even a pie graph could better represent the data (and the story) he was trying to get across. Overall, Saiyaz used very interesting data and did a good job at isolating the variables of interest although his visualization could have used some improvement.

### Project 2
Junho Moon's Final Project - "World Military" - was very fun to explore. It was detailed and well-developed. Taking data from the International Institute for Strategic Studies, The Military Balance; Stockholm International Peace Research Institute (SIPRI), Arms Tranfer Database; Stockholm International Peace Research Institute (SIPRI), Yearbook: Armaments, Disarmament and International Security; and the Bulletin of the Atomic Scientists, Junho allows us to compare coutry's military personnel, spending, and arms trade to each other, to world regions, and to the world as a whole over the latter half of the 20th century up to 2017. His interactive graphs were very useful in representing his data and allowing the viewer to zoom in on particular sections that might be of interest. The first tab on personnel number and percentages has the corresponding data by income level, which allows us to compare number and percentage of military personel by class within a country. His tab on trade has several subtabs outlining imports and exports over time, top expporters and importers, and weaponry categories. He further adds interactive commands that allows us to see how international organizations and rebel groups participated in this arm trade. His additional tab on nuclear use/management is also very useful and detailed portraying the use/access of nuclear weaponry by country over time. However, there were some small issues. The y scale on the personnel tab is not very good because the labels are unclear to the lay eye. In the trade tab, under exports over time, he has an income option that does not make a lot of sense for the data being explored (and differs from his imports over time subtab, which has rebel forces and international organizations). Apart from these minor mistakes, Junho brought together a lot of data and did a great job of visualizing it into a coherent application that offers a wealth of information on the world's military. 